# jwt configuration
jwt:
  signing-key: 'qmPlus'
  expires-time: 604800
  buffer-time: 86400

# redis configuration
redis:
  db: 0
  addr: '127.0.0.1:6379'
  password: ''

# captcha configuration
captcha:
  key-long: 4
  img-width: 180
  img-height: 80


# mysql connect configuration
mysql:
  path: '127.0.0.1:3306'
  config: 'charset=utf8&parseTime=true'
  db-name: 'gin'
  username: 'root'
  password: ''
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: false
  log-zap: ""

# system configuration
system:
  addr: 8991
  use-multipoint: true    # 多点登录拦截，true为拦截，false为不拦截

# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[I-ADMIN]'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true