# jwt configuration
jwt:
  signing-key: 'qmPlus'
  expires-time: 604800
  buffer-time: 86400

# redis configuration
redis:
  db: 0
  addr: '127.0.0.1:6379'
  password: ''

# captcha configuration
captcha:
  key-long: 4
  img-width: 180
  img-height: 80


# mysql connect configuration
mysql:
  path: '127.0.0.1:3306'
  config: 'charset=utf8&parseTime=true'
  db-name: 'gin'
  username: 'root'
  password: ''
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: false
  log-zap: ""

# system configuration
system:
  env: 'develop'  # Change to "develop" to skip authentication for development mode
  addr: 8991
  use-multipoint: true    # 多点登录拦截，true为拦截，false为不拦截

# zap logger configuration
zap:
  level: 'info'
  format: 'console'
  prefix: '[I-ADMIN]'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true

# casbin configuration
casbin:
  model-path: './resource/rbac_model.conf'

# file configuration
file:
  # 允许上传的最大文件大小 3M
  max-upload-size: 3145728
  file-local-dir: './uploads/file'
  allow-file-type: 'jpg|png|xlsx'
  # 允许下载的最大文件大小 300KB 30720Bytes
  max-download-size: 307200

# excel configuration
excel:
  # excel文件的存放路径
  excel-store-dir: './uploads/excel'